version: "3.9"

services:
  dc-postgres:
    image: "postgres:latest"
    ports:
      - "${PORT_EXT}:${PORT_CON}"
    environment:
      POSTGRES_DB: empresadb
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ~/dev/PostgreSQL:/var/lib/postgresql/data
